// remix/app/root.tsx
import type { MetaFunction } from "@remix-run/node";
import {
  Links,
  LiveReload,
  Meta,
  Outlet,
  Scripts,
  ScrollRestoration,
} from "@remix-run/react";
import { createExtracts, SystemProvider } from './theme'


export const meta: MetaFunction = () => ({
  charset: "utf-8",
  title: "New Remix App",
  viewport: "width=device-width,initial-scale=1",
});

export default function App() {
  const { ExtractElement } = createExtracts()


  return (
    <html lang="en">
      <head>
        <ExtractElement />
        <Meta />
        <Links />
      </head>
      <body>
        <SystemProvider>
          <Outlet />
        </SystemProvider>
        <ScrollRestoration />
        <Scripts />
        <LiveReload />
      </body>
    </html>
  );
}

// solid-start/src/root.tsx
// @refresh reload
import { Suspense } from 'solid-js'
import {
  Body,
  ErrorBoundary,
  FileRoutes,
  Head,
  Html,
  Meta,
  Routes,
  Scripts,
  Style
} from 'solid-start'
import { SystemProvider, createExtracts } from './theme'

import './root.css'

export default function Root() {
  const { extractElement } = createExtracts()
  return (
    <Html lang="en">
      <Head>
        <Meta charset="utf-8" />
        <Meta name="viewport" content="width=device-width, initial-scale=1" />
        {extractElement}
      </Head>
      <Body>
        <Suspense>
          <ErrorBoundary>
            <a href="/">Index</a>
            <a href="/about">About</a>
            <SystemProvider>
              <Routes>
                <FileRoutes />
              </Routes>
            </SystemProvider>
          </ErrorBoundary>
        </Suspense>
        <Scripts />
      </Body>
    </Html>
  )
}
