// vite-ssr-soild/client/src/pages/about.tsx
import { Component, createSignal, onCleanup, onMount } from 'solid-js'
import { styled } from '@styils/solid'

const Button = styled('button', {
  color: 'red'
})

function AA() {
  return <div>hello as</div>
}

const About: Component = () => {
  const [count, setCount] = createSignal(0)
  let interval = null

  onMount(() => {
    interval = setInterval(() => setCount(count() + 1), 1000)
  })

  onCleanup(() => {
    clearInterval(interval)
  })

  return (
    <>
      <h3>About</h3>
      <Button>hello about</Button>
      <AA />
      <span>Time on page: {count()}sec</span>
    </>
  )
}

export default About

// vite-ssr-react/src/pages/About.jsx
import { addAndMultiply } from '../add'
import { multiplyAndAdd } from '../multiply'
import { styled } from '@styils/react'

const Button = styled('button', {
  color: 'red'
})

export default function About() {
  return (
    <>
      <h1>About</h1>
      <Button>hello about</Button>
      <div>{addAndMultiply(1, 2, 3)}</div>
      <div>{multiplyAndAdd(1, 2, 3)}</div>
    </>
  )
}
